### ISSUE TITLE
Task: Migrate all queries used in mainnet solver accounting to this repo

### ISSUE THREAD

**Issue by harisang** [cowprotocol/dune-queries#28]
This is part of [Epic 7.1](https://github.com/cowprotocol/pm/issues/80) for improving our accounting processes.

- [x] The goal is to migrate, review and simplify all queries used in the mainnet payouts script and relevant dashboards to this repo. This includes (at least) the following query ids:
    - [x] [3333356](https://github.com/cowprotocol/dune-queries/pull/19)
    - [x] [1541516](https://github.com/cowprotocol/dune-queries/pull/19)
    - [x] [4056263](https://github.com/cowprotocol/dune-queries/pull/19)
    - [x] [4017925](https://github.com/cowprotocol/dune-queries/pull/14)
    - [x] 3427730
    - [x] 2510345
    - [x] [3602560](https://github.com/cowprotocol/dune-queries/pull/29)
- [ ] Create clean query that provides all relevant info for debugging its payment on a per transaction basis

**Comment by fleupold** [comment]
Do we have a list of Dune queries that needs to be converted?

**Comment by harisang** [comment]
> Do we have a list of Dune queries that needs to be converted?

Added some query ids but i don't know if this is exhaustive

**Comment by fleupold** [comment]
This is done
