### ISSUE TITLE
Adapt protocol and partner fee queries to work on other chains

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/dune-queries#92]
The query https://github.com/cowprotocol/dune-queries/blob/main/cowprotocol/accounting/rewards/mainnet/partner_fees_query_3602560.sql used for accounting does not yet accept a blockchain parameter. The same holds for the query https://dune.com/queries/3703312 which is used for accounting but is not under version control yet.

Additionally, those queries should return values in native tokens and ETH, while it currently only has values in ETH.

**Comment by harisang** [comment]
Addressed by the following PRs

https://github.com/cowprotocol/dune-queries/pull/96
https://github.com/cowprotocol/dune-queries/pull/99
